version: '3.8'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    # develop:
    #   watch:
    #     - path: ./package.json
    #       action: rebuild
    #     - path: ./next.config.js
    #       action: rebuild
    #     - path: .
    #       target: /frontend
    #       action: sync
          
    # depends_on:
    #   - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "5328:5328"