# version: '3'
# services:
#   frontend:
#     build: 
#       context: .
#       dockerfile: Dockerfile.frontend
#     ports:
#       - "7860:7860"

#     # depends_on:
#     #   - backend

#   backend:
#     build:
#       context: ./api
#       dockerfile: Dockerfile.backend
#     ports:
#       - "5328:5328"

version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "5328:5328"

